create table if not exists public.fgi_calls (
  id uuid primary key default gen_random_uuid(),
  thread_id uuid not null references public.fgi_threads(id) on delete cascade,
  caller_id uuid not null references auth.users(id) on delete cascade,
  callee_id uuid not null references auth.users(id) on delete cascade,
  kind text not null default 'audio',
  status text not null default 'ringing',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  answered_at timestamptz,
  ended_at timestamptz,
  constraint fgi_calls_no_self check (caller_id <> callee_id),
  constraint fgi_calls_kind_check check (kind in ('audio','video')),
  constraint fgi_calls_status_check check (status in ('ringing','accepted','declined','ended','missed'))
);

create unique index if not exists fgi_calls_one_active_thread_idx
  on public.fgi_calls(thread_id)
  where status in ('ringing','accepted');

create index if not exists fgi_calls_callee_status_idx
  on public.fgi_calls(callee_id,status,created_at desc);

create table if not exists public.fgi_call_signals (
  id bigint generated by default as identity primary key,
  call_id uuid not null references public.fgi_calls(id) on delete cascade,
  sender_id uuid not null references auth.users(id) on delete cascade,
  signal_type text not null,
  payload jsonb not null,
  created_at timestamptz not null default now(),
  constraint fgi_call_signals_type_check check (signal_type in ('offer','answer','ice')),
  constraint fgi_call_signals_payload_check check (octet_length(payload::text) <= 100000)
);

create index if not exists fgi_call_signals_call_id_id_idx
  on public.fgi_call_signals(call_id,id);

alter table public.fgi_calls enable row level security;
alter table public.fgi_call_signals enable row level security;

revoke all on public.fgi_calls from anon, authenticated;
grant select(id,thread_id,caller_id,callee_id,kind,status,created_at,updated_at,answered_at,ended_at)
  on public.fgi_calls to authenticated;
grant insert(thread_id,caller_id,callee_id,kind)
  on public.fgi_calls to authenticated;
grant update(status)
  on public.fgi_calls to authenticated;

revoke all on public.fgi_call_signals from anon, authenticated;
grant select(id,call_id,sender_id,signal_type,payload,created_at)
  on public.fgi_call_signals to authenticated;
grant insert(call_id,sender_id,signal_type,payload)
  on public.fgi_call_signals to authenticated;

drop policy if exists fgi_calls_read on public.fgi_calls;
create policy fgi_calls_read
on public.fgi_calls
for select to authenticated
using ((select auth.uid()) in (caller_id,callee_id));

drop policy if exists fgi_calls_insert on public.fgi_calls;
create policy fgi_calls_insert
on public.fgi_calls
for insert to authenticated
with check (
  caller_id = (select auth.uid())
  and exists (
    select 1 from public.fgi_threads t
    where t.id = fgi_calls.thread_id
      and (
        (t.client_id = fgi_calls.caller_id and t.coach_id = fgi_calls.callee_id)
        or
        (t.coach_id = fgi_calls.caller_id and t.client_id = fgi_calls.callee_id)
      )
  )
);

drop policy if exists fgi_calls_update on public.fgi_calls;
create policy fgi_calls_update
on public.fgi_calls
for update to authenticated
using ((select auth.uid()) in (caller_id,callee_id))
with check ((select auth.uid()) in (caller_id,callee_id));

drop policy if exists fgi_call_signals_read on public.fgi_call_signals;
create policy fgi_call_signals_read
on public.fgi_call_signals
for select to authenticated
using (
  exists (
    select 1 from public.fgi_calls c
    where c.id = fgi_call_signals.call_id
      and (select auth.uid()) in (c.caller_id,c.callee_id)
  )
);

drop policy if exists fgi_call_signals_insert on public.fgi_call_signals;
create policy fgi_call_signals_insert
on public.fgi_call_signals
for insert to authenticated
with check (
  sender_id = (select auth.uid())
  and exists (
    select 1 from public.fgi_calls c
    where c.id = fgi_call_signals.call_id
      and (select auth.uid()) in (c.caller_id,c.callee_id)
      and c.status in ('ringing','accepted')
  )
);

create or replace function fgi_private.expire_stale_fgi_calls()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  update public.fgi_calls
     set status='missed', ended_at=now(), updated_at=now()
   where thread_id=new.thread_id
     and status='ringing'
     and created_at < now() - interval '90 seconds';
  return new;
end
$$;
revoke all on function fgi_private.expire_stale_fgi_calls() from public,anon,authenticated;

drop trigger if exists fgi_calls_expire_stale on public.fgi_calls;
create trigger fgi_calls_expire_stale
before insert on public.fgi_calls
for each row execute function fgi_private.expire_stale_fgi_calls();

create or replace function fgi_private.guard_fgi_call()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
declare actor uuid := auth.uid();
begin
  if tg_op='INSERT' then
    if actor is null or new.caller_id <> actor or new.status <> 'ringing'
       or new.answered_at is not null or new.ended_at is not null then
      raise exception 'Invalid call creation' using errcode='42501';
    end if;
    if not exists (
      select 1 from public.fgi_threads t
      where t.id=new.thread_id
        and (
          (t.client_id=new.caller_id and t.coach_id=new.callee_id)
          or
          (t.coach_id=new.caller_id and t.client_id=new.callee_id)
        )
    ) then
      raise exception 'Call participants do not match thread' using errcode='42501';
    end if;
    return new;
  end if;

  if new.id is distinct from old.id
     or new.thread_id is distinct from old.thread_id
     or new.caller_id is distinct from old.caller_id
     or new.callee_id is distinct from old.callee_id
     or new.kind is distinct from old.kind
     or new.created_at is distinct from old.created_at then
    raise exception 'Call identity cannot be changed' using errcode='42501';
  end if;

  if actor is null or actor not in (old.caller_id,old.callee_id) then
    raise exception 'Not a call participant' using errcode='42501';
  end if;

  if new.status is distinct from old.status then
    if old.status='ringing' and new.status='accepted' and actor=old.callee_id then
      new.answered_at=coalesce(old.answered_at,now());
    elsif old.status='ringing' and new.status='declined' and actor=old.callee_id then
      new.ended_at=coalesce(old.ended_at,now());
    elsif old.status in ('ringing','accepted') and new.status='ended' then
      new.ended_at=coalesce(old.ended_at,now());
    else
      raise exception 'Invalid call status transition' using errcode='42501';
    end if;
  end if;

  new.updated_at=now();
  return new;
end
$$;
revoke all on function fgi_private.guard_fgi_call() from public,anon,authenticated;

drop trigger if exists fgi_calls_guard on public.fgi_calls;
create trigger fgi_calls_guard
before insert or update on public.fgi_calls
for each row execute function fgi_private.guard_fgi_call();

notify pgrst,'reload schema';
